server:
  port: 8081

spring:
  application:
    name: member-service
  datasource:
    url: jdbc:mysql://localhost:3306/optum_member_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
