
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notificationdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show:sql: true

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
custom:
  kafka:
    groups:
      notif-group:
        group-id: notif-group
        topic: notifications
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
